name:                hanabi
version:             0.1.0.0
github:              "lehmacdj/hanabi"
license:             BSD3
author:              "Devin Lehmacher"
maintainer:          "lehmacdj@gmail.com"
copyright:           "Copyright: (c) 2017 Devin Lehmacher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Miscellaneous

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lehmacdj/hanabi#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- classy-prelude
- conduit
- containers
- exceptions
- first-class-families
- generic-lens
- haskeline
- lens
- megaparsec
- polysemy
- polysemy-RandomFu
- polysemy-zoo
- random
- random-fu
- refined
- servant
- servant-server
- servant-websockets
- uuid

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
- -Wall
- -Wno-name-shadowing

library:
  source-dirs: src

executables:
  hanabi-console:
    main:                Main.hs
    source-dirs:         app/console
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanabi

tests:
  hanabi-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanabi
    - tasty
    - tasty-hunit
    - tasty-discover
    - tasty-quickcheck
